@startuml start stop

if (Находится ли комната в аварийном состоянии?) then (да)
  :Не заселять студента
 Не изменять статус комнаты;

else
  if (Количество заселенных студентов меньше 3 человек?) then (да)
    :Заселить студента;
    :Изменить статус комнаты на "Занята";
   else
    :Не заселять студента;

@enduml